# Generated by Django 6.1.1 on 2026-10-02 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_seed_dms_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employment_status', 'SEPARATED'), _negated=True), models.Q(('account_status', 'ACTIVE'), _negated=True), _connector='OR'), name='separated_employee_account_not_active'),
        ),
    ]
