# Generated by Django 6.1.1 on 2026-10-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0003_employeeprofile_separated_employee_account_not_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationauditevent',
            name='subject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_audit_events', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='organizationauditevent',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User onboarded'), ('PROFILE_CREATED', 'Employee profile created'), ('PROFILE_UPDATED', 'Employee profile updated'), ('DEPARTMENT_CREATED', 'Department created'), ('DEPARTMENT_UPDATED', 'Department updated'), ('POSITION_CREATED', 'Position created'), ('POSITION_UPDATED', 'Position updated'), ('ASSIGNMENT_CREATED', 'Assignment created'), ('ASSIGNMENT_ENDED', 'Assignment ended'), ('EMPLOYEE_TRANSFERRED', 'Employee transferred'), ('ACCOUNT_STATUS_CHANGED', 'Account status changed'), ('ROLE_CHANGED', 'Role changed'), ('GROUP_PERMISSIONS_CHANGED', 'Group permissions changed')], max_length=32),
        ),
    ]
