# Generated by Django 6.1.1 on 2026-10-02 10:44

from django.db import migrations, models


def backfill_assignment_snapshots(apps, schema_editor):
    Assignment = apps.get_model("organization", "EmployeeAssignment")
    alias = schema_editor.connection.alias
    # The assignment and related rows do not retain rename history. Copying
    # their current labels would silently claim those values were historical.
    # Preserve unknown history as blank; new assignments capture snapshots at
    # creation time in the model/service layer.
    Assignment.objects.using(alias).update(
        department_code_snapshot="",
        department_name_snapshot="",
        position_code_snapshot="",
        position_title_snapshot="",
        supervisor_staff_id_snapshot="",
        supervisor_name_snapshot="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationauditevent_subject_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='department_code_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='department_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='position_code_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=48),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='position_title_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='supervisor_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='supervisor_staff_id_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.RunPython(backfill_assignment_snapshots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.CheckConstraint(condition=models.Q(('supervisor__isnull', True), models.Q(('supervisor', models.F('employee')), _negated=True), _connector='OR'), name='assignment_no_self_supervision'),
        ),
    ]
