# Generated by Django 6.1.1 on 2026-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_employeeassignment_department_code_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationauditevent',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User onboarded'), ('PROFILE_CREATED', 'Employee profile created'), ('PROFILE_UPDATED', 'Employee profile updated'), ('DEPARTMENT_CREATED', 'Department created'), ('DEPARTMENT_UPDATED', 'Department updated'), ('POSITION_CREATED', 'Position created'), ('POSITION_UPDATED', 'Position updated'), ('ASSIGNMENT_CREATED', 'Assignment created'), ('ASSIGNMENT_ENDED', 'Assignment ended'), ('EMPLOYEE_TRANSFERRED', 'Employee transferred'), ('ACCOUNT_STATUS_CHANGED', 'Account status changed'), ('ROLE_CHANGED', 'Role changed'), ('USER_PERMISSIONS_CHANGED', 'User permissions changed'), ('GROUP_PERMISSIONS_CHANGED', 'Group permissions changed')], max_length=32),
        ),
    ]
