# Generated by Django 6.1.1 on 2026-10-02 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_internal_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.CheckConstraint(condition=models.Q(('can_download', False), ('can_view', True), _connector='OR'), name='document_download_requires_view'),
        ),
    ]
