# Generated by Django 6.1.1 on 2026-10-02 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentaccess_document_download_requires_view'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-modified_at', '-pk'], 'permissions': [('download_document', 'Can download permitted DMS documents'), ('review_document', 'Can review assigned DMS documents'), ('reassign_workflow_tasks', 'Can reassign pending DMS workflow tasks')]},
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_audit_events', to='organization.employeeassignment'),
        ),
        migrations.AddField(
            model_name='document',
            name='originating_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originating_documents', to='organization.employeeassignment'),
        ),
        migrations.AddField(
            model_name='workflowdecision',
            name='actor_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_decisions', to='organization.employeeassignment'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='actor_type',
            field=models.CharField(choices=[('SELECTED_USER', 'Selected reviewer'), ('DOCUMENT_CREATOR', 'Document creator'), ('CREATOR_SUPERVISOR', 'Creator supervisor'), ('DEPARTMENT_HEAD', 'Department head')], default='SELECTED_USER', max_length=32),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='assigned_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_tasks', to='organization.employeeassignment'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('DRAFT_SAVED', 'Draft saved'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Review started'), ('RETURNED', 'Returned for revision'), ('REVISION_SAVED', 'Revision saved'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('ARCHIVED', 'Archived'), ('VIEWED', 'Viewed'), ('PDF_VIEWED', 'PDF viewed'), ('DOWNLOADED', 'Downloaded'), ('ATTACHMENT_VIEWED', 'Attachment viewed'), ('REASSIGNED', 'Workflow task reassigned')], max_length=24),
        ),
        migrations.CreateModel(
            name='WorkflowTaskReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dms_task_reassignments_made', to=settings.AUTH_USER_MODEL)),
                ('new_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassignments_to', to='organization.employeeassignment')),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dms_tasks_reassigned_to', to=settings.AUTH_USER_MODEL)),
                ('previous_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassignments_from', to='organization.employeeassignment')),
                ('previous_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dms_tasks_reassigned_from', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassignments', to='documents.workflowtask')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'default_permissions': ('view',),
            },
        ),
    ]
